// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Presentacion.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen4.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_iso_teslagen_png);    // assets/iso_teslagen.png
LV_IMG_DECLARE(ui_img_icono_configuracion_small_png);    // assets/icono_configuracion_small.png

// FONTS
LV_FONT_DECLARE(ui_font_PoppinsBlack40);
LV_FONT_DECLARE(ui_font_PoppinsBlack25);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
