// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: texel_t1

#include "../ui.h"

lv_obj_t * ui_Perfil = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
// event funtions
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Trabajando, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Trabajando_screen_init);
    }
}

// build funtions

void ui_Perfil_screen_init(void)
{
    ui_Perfil = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Perfil, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Perfil);
    lv_obj_set_width(ui_Keyboard1, 480);
    lv_obj_set_height(ui_Keyboard1, 240);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 120);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextArea1 = lv_textarea_create(ui_Perfil);
    lv_obj_set_width(ui_TextArea1, 299);
    lv_obj_set_height(ui_TextArea1, 40);
    lv_obj_set_x(ui_TextArea1, -49);
    lv_obj_set_y(ui_TextArea1, -144);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_Container1 = lv_obj_create(ui_Perfil);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 480);
    lv_obj_set_height(ui_Container1, 40);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -220);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Perfil);
    lv_obj_set_width(ui_Button1, 40);
    lv_obj_set_height(ui_Button1, 40);
    lv_obj_set_x(ui_Button1, 207);
    lv_obj_set_y(ui_Button1, -221);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_icono_configuracion_small_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Perfil);
    lv_obj_set_width(ui_TextArea2, 299);
    lv_obj_set_height(ui_TextArea2, 40);
    lv_obj_set_x(ui_TextArea2, -49);
    lv_obj_set_y(ui_TextArea2, -88);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Perfil_screen_destroy(void)
{
    if(ui_Perfil) lv_obj_del(ui_Perfil);

    // NULL screen variables
    ui_Perfil = NULL;
    ui_Keyboard1 = NULL;
    ui_TextArea1 = NULL;
    ui_Container1 = NULL;
    ui_Button1 = NULL;
    ui_TextArea2 = NULL;

}
