// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: texel_t1

#include "../ui.h"

lv_obj_t * ui_Presentacion = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_Presentacion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Perfil, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Perfil_screen_init);
    }
}

// build funtions

void ui_Presentacion_screen_init(void)
{
    ui_Presentacion = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Presentacion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Presentacion);
    lv_img_set_src(ui_Image1, &ui_img_iso_teslagen_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -1);
    lv_obj_set_y(ui_Image1, -4);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Presentacion, ui_event_Presentacion, LV_EVENT_ALL, NULL);

}

void ui_Presentacion_screen_destroy(void)
{
    if(ui_Presentacion) lv_obj_del(ui_Presentacion);

    // NULL screen variables
    ui_Presentacion = NULL;
    ui_Image1 = NULL;

}
