// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PRESENTACION_H
#define UI_PRESENTACION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Presentacion
extern void ui_Presentacion_screen_init(void);
extern void ui_Presentacion_screen_destroy(void);
extern void ui_event_Presentacion(lv_event_t * e);
extern lv_obj_t * ui_Presentacion;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

