// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: texel_t1

#ifndef UI_PERFIL_H
#define UI_PERFIL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Perfil
extern void ui_Perfil_screen_init(void);
extern void ui_Perfil_screen_destroy(void);
extern lv_obj_t * ui_Perfil;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Container1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_TextArea2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

