// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern void ui_event_Container3(lv_event_t * e);
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label6;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

