// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_TabView3 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_TabPage3 = NULL;
// event funtions
void ui_event_TabPage3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Presentacion, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Presentacion_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView3 = lv_tabview_create(ui_Screen2, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView3, 480);
    lv_obj_set_height(ui_TabView3, 480);
    lv_obj_set_align(ui_TabView3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView3, "Modo Emision");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView3, "Modo Trabajo");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView3, "Configuracion");

    lv_obj_add_event_cb(ui_TabPage3, ui_event_TabPage3, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_TabView3 = NULL;
    ui_TabPage1 = NULL;
    ui_TabPage2 = NULL;
    ui_TabPage3 = NULL;

}
