// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: texel_t1

#include "../ui.h"

lv_obj_t * ui_Trabajando = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Roller3 = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Button4 = NULL;
// event funtions
void ui_event_Container3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_slider_set_text_value(ui_Label6, target, "", "%");
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_slider_set_text_value(ui_Label6, target, "", "%");
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_set_text_value(ui_Label6, target, "", "%");
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ModoTrabajo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ModoTrabajo_screen_init);
    }
}

// build funtions

void ui_Trabajando_screen_init(void)
{
    ui_Trabajando = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Trabajando, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Trabajando);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 480);
    lv_obj_set_height(ui_Container3, 150);
    lv_obj_set_x(ui_Container3, -3);
    lv_obj_set_y(ui_Container3, -108);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -30);
    lv_obj_set_y(ui_Label5, -50);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Potencia");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_PoppinsBlack25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel1, 120);
    lv_obj_set_height(ui_Panel1, 45);
    lv_obj_set_x(ui_Panel1, 94);
    lv_obj_set_y(ui_Panel1, -51);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "0%");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_PoppinsBlack40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Container3);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 300);
    lv_obj_set_height(ui_Slider2, 30);
    lv_obj_set_x(ui_Slider2, -4);
    lv_obj_set_y(ui_Slider2, -4);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    ui_Container4 = lv_obj_create(ui_Trabajando);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 430);
    lv_obj_set_height(ui_Container4, 131);
    lv_obj_set_x(ui_Container4, 1);
    lv_obj_set_y(ui_Container4, 125);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -79);
    lv_obj_set_y(ui_Label7, -22);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Tiempo restante");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_PoppinsBlack25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 40);
    lv_obj_set_x(ui_Panel2, 88);
    lv_obj_set_y(ui_Panel2, -21);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "10:22");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_PoppinsBlack25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -132);
    lv_obj_set_y(ui_Button2, 29);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Iniciar");

    ui_Button3 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -18);
    lv_obj_set_y(ui_Button3, 29);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Detener");

    ui_Roller3 = lv_roller_create(ui_Trabajando);
    lv_roller_set_options(ui_Roller3, "Facial\nCorporal", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller3, 115);
    lv_obj_set_width(ui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller3, -92);
    lv_obj_set_y(ui_Roller3, -8);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);

    ui_Roller1 = lv_roller_create(ui_Trabajando);
    lv_roller_set_options(ui_Roller1, "Continuo\nIntermitente", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 102);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 80);
    lv_obj_set_y(ui_Roller1, -5);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Container2 = lv_obj_create(ui_Trabajando);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 480);
    lv_obj_set_height(ui_Container2, 40);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -220);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Trabajando);
    lv_obj_set_width(ui_Button4, 40);
    lv_obj_set_height(ui_Button4, 40);
    lv_obj_set_x(ui_Button4, 210);
    lv_obj_set_y(ui_Button4, -220);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button4, &ui_img_icono_configuracion_small_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container3, ui_event_Container3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Trabajando_screen_destroy(void)
{
    if(ui_Trabajando) lv_obj_del(ui_Trabajando);

    // NULL screen variables
    ui_Trabajando = NULL;
    ui_Container3 = NULL;
    ui_Label5 = NULL;
    ui_Panel1 = NULL;
    ui_Label6 = NULL;
    ui_Slider2 = NULL;
    ui_Container4 = NULL;
    ui_Label7 = NULL;
    ui_Panel2 = NULL;
    ui_Label8 = NULL;
    ui_Button2 = NULL;
    ui_Label4 = NULL;
    ui_Button3 = NULL;
    ui_Label1 = NULL;
    ui_Roller3 = NULL;
    ui_Roller1 = NULL;
    ui_Container2 = NULL;
    ui_Button4 = NULL;

}
